# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

def common
pod 'SkyScraper/Base', :git => "git@github.com:justadreamer/SkyScraper.git"
pod 'SwiftyJSON', '~> 2.3'
end

target 'SwiftySky' do
common
end

target 'SwiftySkyTests' do
common
end
